#!/usr/bin/env bash
set -euo pipefail

log() {
	printf '%s\n' "$*"
}

dbg() {
	if [ "${DEBUG:-false}" = "true" ]; then
		printf '%s\n' "$*"
	fi
}

BASE_CONFIG_FILE="/etc/snmp/snmpd.conf"
RUNTIME_CONFIG_FILE="/run/snmpd/snmpd.conf"
MOUNT_INFO="/proc/self/mountinfo"

# Configuration default values

# Enforced configuration options
export SNMPD_AGENTADDRESS="udp:0.0.0.0:10161,tcp:0.0.0.0:10161"

declare -A NAMED_OPTIONS
declare -a APPEND_LINES
declare -A V3_USERS

if ! grep -qE '[[:space:]]/host_proc[[:space:]]' "$MOUNT_INFO"; then
	log "ERROR: /host_proc is not mounted. Start container with: -v /proc:/host_proc:ro" >&2
	exit 1
fi

mkdir -p /run/snmpd

while IFS='=' read -r name value; do
	case "${name}" in
		SNMPD_CUST_*)
			[[ -n "${value}" ]] && APPEND_LINES+=("${value}")
			;;
		SNMPD_V3_*|SNMPV_V3_*)
			continue
			;;
		SNMPD_*)
			option_name="${name#SNMPD_}"
			if [[ -n "${option_name}" && -n "${value}" ]]; then
				option_name="$(printf '%s' "${option_name}" | tr '[:upper:]' '[:lower:]')"
				NAMED_OPTIONS["${option_name}"]="${value}"
			fi
			;;
	esac
done < <(env | LC_ALL=C sort)

if grep -qE "[[:space:]]${BASE_CONFIG_FILE}[[:space:]]" "${MOUNT_INFO}" && [[ -f "${BASE_CONFIG_FILE}" ]]; then
	log "Using mounted ${BASE_CONFIG_FILE} as base config"
	cp "${BASE_CONFIG_FILE}" "${RUNTIME_CONFIG_FILE}"
else
	log "No base config found, generating config"
	cat > "${RUNTIME_CONFIG_FILE}" <<'EOF'
# Generated by entrypoint
EOF
fi

if [[ ${#NAMED_OPTIONS[@]} -gt 0 ]]; then
	for option_name in "${!NAMED_OPTIONS[@]}"; do
		dbg "Checking whether parameter '${option_name}' exists in existing config"
		if grep -qE "^[[:space:]]*${option_name}([[:space:]]|$)" "${RUNTIME_CONFIG_FILE}"; then
			log "Disabling existing '${option_name}' directive"
			awk -v option="${option_name}" '
				BEGIN { regex = "^[[:space:]]*" option "([[:space:]]|$)" }
				$0 ~ regex && $0 !~ /^[[:space:]]*#/ { print "# " $0; next }
				{ print }
			' "${RUNTIME_CONFIG_FILE}" > "${RUNTIME_CONFIG_FILE}.tmp"
			mv "${RUNTIME_CONFIG_FILE}.tmp" "${RUNTIME_CONFIG_FILE}"
		else
			dbg "No existing '${option_name}' directive found"
		fi
	done
fi

{
	echo ""
	echo "# ---- options generated by entrypoint ----"
	if [[ ${#NAMED_OPTIONS[@]} -gt 0 ]]; then
		while IFS= read -r option_name; do
			printf '%s %s\n' "${option_name}" "${NAMED_OPTIONS[${option_name}]}"
		done < <(printf '%s\n' "${!NAMED_OPTIONS[@]}" | LC_ALL=C sort)
	fi
	if [[ ${#APPEND_LINES[@]} -gt 0 ]]; then
		printf '%s\n' "${APPEND_LINES[@]}"
	fi
} >> "${RUNTIME_CONFIG_FILE}"

dbg "Assembled runtime config at ${RUNTIME_CONFIG_FILE}:"
if [ "${DEBUG:-false}" = "true" ]; then
	sed 's/^/ > /' "${RUNTIME_CONFIG_FILE}"
fi

log "Starting snmpd process"
exec /usr/local/sbin/snmpd -f -c "${RUNTIME_CONFIG_FILE}"
